import { CanonicalDisputeEvent } from '../../../schemas/canonical-dispute';
import { ForensicAnalysisResult } from '../../ai/forensic-sensor.service';
import { DecisionResult } from '../../decision-engine.service';
import { ArbitrationStrategy } from '../dossier.strategy';

export class TikTokArbitrationStrategy implements ArbitrationStrategy {
  supports(marketplace: string): boolean {
    return marketplace === 'TIKTOK_SHOP';
  }

  generateDossier(event: CanonicalDisputeEvent, aiResult: ForensicAnalysisResult, decision: DecisionResult): string {
    return `
# TIKTOK SHOP - DISPUTE ESCALATION DOSSIER
**Order ID:** ${event.order.order_id}
**Tracking Number:** ${event.logistics.tracking_number}

## 1. Policy Violation Context
In accordance with the **TikTok Shop Customer Order Return Policy**, the Seller rejects this refund request. The empirical evidence heavily suggests logistics tampering or buyer fraud.

## 2. SentinelOps AI Forensic Telemetry
- **Absolute Discrepancy:** ${aiResult.weight_discrepancy_grams}g
- **Manifested Weight (Catalog):** ${event.evidence.catalog_weight_grams}g
- **Courier Handover Weight:** ${event.logistics.driver_handover_weight_grams}g
- **Visual Evidence Match:** ${Math.round(aiResult.visual_evidence_match_rating * 100)}%
- **System Fraud Risk Score:** ${aiResult.fraud_risk_score}/100

## 3. Resolution Request
The automated decision matrix has classified this incident as **${decision.decision_lane}**.
We request TikTok Shop moderation to release the frozen funds back to the merchant, as the item was properly handed over to ${event.logistics.courier_code} based on first-mile injection scans.

---
*Auto-generated by SentinelOps AI Arbitration Engine.*
    `.trim();
  }
}
