name: CI

on:
  push:
    branches: [ "development", "main", "master" ]
  pull_request:
    branches: [ "development", "main", "master" ]

jobs:
  build:
    name: ci/build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install Dependencies
        run: pnpm install --ignore-scripts

      - name: Type Check
        run: pnpm tsc --noEmit

      - name: Run Unit Tests
        run: pnpm test
